[package]
name = "gandalf_bot"
version = "0.1.0"
edition = "2021"
description = ""
readme = "README.md"
homepage = "https://github.com/celeo/gandalf_bot"
repository = "https://github.com/celeo/gandalf_bot"
license = "MIT OR Apache-2.0"
exclude = [
  ".github"
]

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.3"
chrono = "0.4.28"
chrono-tz = "0.8.3"
dotenv = "0.15.0"
log = "0.4.20"
once_cell = "1.18.0"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
regex = "1.9.4"
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["full"] }
twilight-gateway = "0.15.2"
twilight-http = "0.15.2"
twilight-interactions = "0.15.1"
twilight-model = "0.15.2"
twilight-util = { version = "0.15.2", features = ["builder"] }
