[package]
name = "gandalf_bot"
version = "1.0.0"
edition = "2021"
description = ""
readme = "README.md"
homepage = "https://github.com/celeo/gandalf_bot"
repository = "https://github.com/celeo/gandalf_bot"
license = "MIT OR Apache-2.0"
exclude = [
  ".github"
]

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
chrono = "0.4.45"
chrono-tz = "0.10.4"
log = "0.4.33"
pretty_env_logger = "0.5.0"
rand = "0.10.2"
regex = "1.13.1"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
twilight-gateway = "0.17.1"
twilight-http = "0.17.1"
twilight-interactions = "0.17.1"
twilight-model = "0.17.1"
twilight-util = { version = "0.17.0", features = ["builder"] }
