app = "celeo-gandalf-bot"
primary_region = "lax"

[checks]
  [checks.tcp_health]
    type = "tcp"
    grace_period = "1m"
    interval = "5m"
    port = 8000
    timeout = "10s"
    restart_limit = 3
