name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]'))
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.11.3'
      - run: mix deps.get
      - run: mix test
