name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]'))
    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache Rust artifacts
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "0aca4b3d-ab48-4ec0-8044-f2be53fcd69a"
        save-if: ${{ github.ref == 'refs/heads/master' }}
    - name: Install clippy
      run: rustup component add clippy
    - name: Get words
      run: curl -s https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt | tr -d '\r' > words.txt
    - name: Run tests
      run: cargo test --verbose --all
    - name: Run clippy
      run: cargo clippy
